require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.0
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'test/**/*'
    - 'db/**/*'

Performance:
  Exclude:
    - '**/test/**/*'

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true


Layout/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'config/initializers/**/*.rb'
    - 'config/environments/**/*'
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  EnforcedStyle: double_quotes
